package main.java.business.model.enums;

public enum TipoAtaque {
    FORCA, AGILIDADE, INTELECTO, VONTADE, PERCEPCAO,  DEFESA, SAUDE, TXCURA, TAMANHO, DESLOCAMENTO, PODER, DANO, INSANIDADE, CORRUPÇÃO;
}
